### ISSUE TITLE
Multiple Uncaught Errors: Invocation of form runtime.connect(null, )

### ISSUE THREAD

**Issue by antivirtel** [extesy/hoverzoom#243]
Dear Developers,

I got a lots of like this on Gmail in console:
```
Uncaught Error: Invocation of form runtime.connect(null, ) doesn't match definition runtime.connect(optional string extensionId, optional object connectInfo)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at Object.<anonymous> (extensions::binding:411:30)
    at Object.<anonymous> (extensions::runtime:129:24)
    at Object.handleRequest (extensions::binding:63:27)
    at Object.<anonymous> (extensions::binding:422:32)
    at prepareImgLinks (chrome-extension://pccckmaobkjjboncdfnnofkonhgpceea/js/hoverzoom.js:821:32)
extensions::schemaUtils:112 Uncaught Error: Invocation of form runtime.connect(null, ) doesn't match definition runtime.connect(optional string extensionId, optional object connectInfo)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:112:11)
    at Object.<anonymous> (extensions::binding:411:30)
    at Object.<anonymous> (extensions::runtime:129:24)
    at Object.handleRequest (extensions::binding:63:27)
    at Object.<anonymous> (extensions::binding:422:32)
    at prepareImgLinks (chrome-extension://pccckmaobkjjboncdfnnofkonhgpceea/js/hoverzoom.js:821:32)
```

Can you please fix this issue?

Thanks, Roland

**Comment by extesy** [comment]
Hi Roland, please reload the page to get rid of these errors. This is caused by extension updating in the background and not reloading the page.
